package entity.student;

public enum Grade {
    ASSOCIATE,
    CONTINUOUS_BACHELOR,
    DISCONTINUOUS_BACHELOR,
    CONTINUOUS_MASTER,
    DISCONTINUOUS_MASTER,
    DOCTORATE,
    CONTINUOUS_DOCTORATE,
    DISCONTINUOUS_SPECIALIZED_DOCTORATE
}
